"""add indices to imdb ids

Revision ID: 805101fa6f39
Revises: d60ca393f726
Create Date: 2023-07-17 15:41:37.801594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805101fa6f39'
down_revision = 'd60ca393f726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_episodes_imdb_id'), ['imdb_id'], unique=False)

    with op.batch_alter_table('tv_series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tv_series_imdb_id'), ['imdb_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tv_series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tv_series_imdb_id'))

    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_episodes_imdb_id'))

    # ### end Alembic commands ###
