"""create tables

Revision ID: cad379fcb9bc
Revises: 
Create Date: 2023-07-20 15:05:47.505903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cad379fcb9bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('imdb_id', sa.String(), nullable=True),
    sa.Column('primary_title', sa.String(), nullable=False),
    sa.Column('original_title', sa.String(), nullable=True),
    sa.Column('is_adult', sa.Boolean(), nullable=True),
    sa.Column('start_year', sa.String(), nullable=True),
    sa.Column('end_year', sa.String(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('genres', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_titles_imdb_id'), ['imdb_id'], unique=True)

    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imdb_id', sa.String(), nullable=False),
    sa.Column('parent_imdb_id', sa.String(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_imdb_id'], ['titles.imdb_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_episodes_imdb_id'), ['imdb_id'], unique=True)

    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imdb_id', sa.String(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('num_votes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['imdb_id'], ['episodes.imdb_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_episodes_imdb_id'))

    op.drop_table('episodes')
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_titles_imdb_id'))

    op.drop_table('titles')
    # ### end Alembic commands ###
