"""add tv_series table

Revision ID: 403fb0498789
Revises: 
Create Date: 2023-07-05 15:59:39.185969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403fb0498789'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tv_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imdb_id', sa.String(), nullable=True),
    sa.Column('primary_title', sa.String(), nullable=False),
    sa.Column('original_title', sa.String(), nullable=True),
    sa.Column('is_adult', sa.Boolean(), nullable=True),
    sa.Column('start_year', sa.String(), nullable=True),
    sa.Column('end_year', sa.String(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('genres', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imdb_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tv_series')
    # ### end Alembic commands ###
