"""add fk ep to title

Revision ID: 29349ea9d2c8
Revises: cad379fcb9bc
Create Date: 2023-07-26 11:18:21.343788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29349ea9d2c8'
down_revision = 'cad379fcb9bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_ep_title', 'titles', ['imdb_id'], ['imdb_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ep_title', type_='foreignkey')

    # ### end Alembic commands ###
